//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public long OrderID { get; set; }
        public long userID { get; set; }
        public long FoodID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Users Users { get; set; }
    }
}
